id: IFC40E3F5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:45:27+00:00'
last_modified: '2022-06-08T12:10:45.169939+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1104
  title: 'གྲོ་ལོད་ཆོས་སྐོར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E91B:
      image_group_id: I1KG10659
      title: ''
      total_pages: 598
      order: 1
      base_file: E91B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
