id: IFC40E3F5
legacy_id: P009600
ocr_import_info:
  bdrc_scan_id: W4CZ1104
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T17:41:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:23:06.800756+00:00'
last_modified: 2022-09-04 02:23:21.077157
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ1104
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ1104
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲོ་ལོད་ཆོས་སྐོར།
  author: ནུས་ལྡན་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6605384063221366
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG10659:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10659
      total_pages: 598
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10659.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6605384063221366
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
