id: P009600
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ1104
  title: 'གྲོ་ལོད་ཆོས་སྐོར། '
  author: ''
  volumes:
    4afe2f8c114b4cdc87e25a7048672f9c:
      image_group_id: I1KG10659
      title: ''
      volume_number: 1
      total_pages: 598
      base_file: v001.txt
